name: CI

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'barsdiary/**'
      - '.flake8'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'barsdiary/**'
      - '.flake8'

jobs:
  full-testing:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.9

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade/install pip and poetry
        run: python -m pip install --upgrade pip poetry

      - name: Install dependencies
        run: poetry install

      # formatter
      - name: Run black
        run: poetry run black barsdiary --check

      # linters
      - name: Run flake8
        run: poetry run flake8

      - name: Run isort
        run: poetry run isort barsdiary --check --color

      - name: Run mypy
        run: poetry run mypy barsdiary --color-output

      # tests
      - name: Run pytest
        run: poetry run pytest

  testing:
    needs: [full-testing]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
        exclude:
          # this OS and Python were used in full-testing job.
          - os: ubuntu-latest
            python-version: 3.9

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade/install pip and poetry
        run: python -m pip install --upgrade pip poetry

      - name: Install dependencies
        run: poetry install

      # no linters

      # tests
      - name: Run pytest
        run: poetry run pytest
