name: PyPI publish

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # no checking ci.yml
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade/install pip and poetry
        run: python -m pip install --upgrade pip poetry

      - name: Build and publish on pypi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: poetry publish --build --dry-run
